//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.06 at 04:46:28 PM MSK 
//


package ru.cos.nissan.graphs.classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * VerificationManual fig.41. Double graph: Traffic condition diagram upstream of bottleneck and through volume cumulative curve at each observation section
 * 
 * <p>Java class for TrafficTransitionDiagramData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrafficTransitionDiagramData">
 *   &lt;complexContent>
 *     &lt;extension base="{}GraphData">
 *       &lt;sequence>
 *         &lt;element name="cumulativeVolume" type="{}CumulateVolumeData"/>
 *         &lt;element name="distanceFromBottleneck" type="{}DistanceFromBottleneckData"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrafficTransitionDiagramData", propOrder = {
    "cumulativeVolume",
    "distanceFromBottleneck"
})
public class TrafficTransitionDiagramData
    extends GraphData
{

    @XmlElement(required = true)
    protected CumulateVolumeData cumulativeVolume;
    @XmlElement(required = true)
    protected DistanceFromBottleneckData distanceFromBottleneck;

    /**
     * Gets the value of the cumulativeVolume property.
     * 
     * @return
     *     possible object is
     *     {@link CumulateVolumeData }
     *     
     */
    public CumulateVolumeData getCumulativeVolume() {
        return cumulativeVolume;
    }

    /**
     * Sets the value of the cumulativeVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link CumulateVolumeData }
     *     
     */
    public void setCumulativeVolume(CumulateVolumeData value) {
        this.cumulativeVolume = value;
    }

    /**
     * Gets the value of the distanceFromBottleneck property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceFromBottleneckData }
     *     
     */
    public DistanceFromBottleneckData getDistanceFromBottleneck() {
        return distanceFromBottleneck;
    }

    /**
     * Sets the value of the distanceFromBottleneck property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceFromBottleneckData }
     *     
     */
    public void setDistanceFromBottleneck(DistanceFromBottleneckData value) {
        this.distanceFromBottleneck = value;
    }

}
