//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.06 at 04:46:28 PM MSK 
//


package ru.cos.nissan.graphs.classes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * abstract graph data
 * 
 * <p>Java class for GraphData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GraphData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="intervalCollection" type="{}intervalData" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GraphData", propOrder = {
    "intervalCollection"
})
@XmlSeeAlso({
    VolumeMeterData.class,
    HistogramData.class,
    CumulateVolumeData.class,
    DensityFlowData.class,
    CumulateVolumeLightedData.class,
    DistanceFromBottleneckData.class,
    TrafficTransitionDiagramData.class,
    SpeedData.class,
    TravelTimeData.class,
    FlowData.class,
    DensityData.class
})
public abstract class GraphData {

    @XmlElement(required = true)
    protected List<IntervalData> intervalCollection;

    /**
     * Gets the value of the intervalCollection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intervalCollection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntervalCollection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IntervalData }
     * 
     * 
     */
    public List<IntervalData> getIntervalCollection() {
        if (intervalCollection == null) {
            intervalCollection = new ArrayList<IntervalData>();
        }
        return this.intervalCollection;
    }

}
