//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.06 at 04:46:28 PM MSK 
//


package ru.cos.nissan.graphs.classes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.cos.nissan.graphs.classes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.cos.nissan.graphs.classes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DensityFlowData }
     * 
     */
    public DensityFlowData createDensityFlowData() {
        return new DensityFlowData();
    }

    /**
     * Create an instance of {@link VolumeMeterData }
     * 
     */
    public VolumeMeterData createVolumeMeterData() {
        return new VolumeMeterData();
    }

    /**
     * Create an instance of {@link MarkedPoints }
     * 
     */
    public MarkedPoints createMarkedPoints() {
        return new MarkedPoints();
    }

    /**
     * Create an instance of {@link Bars }
     * 
     */
    public Bars createBars() {
        return new Bars();
    }

    /**
     * Create an instance of {@link IntervalData }
     * 
     */
    public IntervalData createIntervalData() {
        return new IntervalData();
    }

    /**
     * Create an instance of {@link CumulateVolumeData }
     * 
     */
    public CumulateVolumeData createCumulateVolumeData() {
        return new CumulateVolumeData();
    }

    /**
     * Create an instance of {@link Interval }
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link DensityData }
     * 
     */
    public DensityData createDensityData() {
        return new DensityData();
    }

    /**
     * Create an instance of {@link DistanceFromBottleneckData }
     * 
     */
    public DistanceFromBottleneckData createDistanceFromBottleneckData() {
        return new DistanceFromBottleneckData();
    }

    /**
     * Create an instance of {@link TrafficTransitionDiagramData }
     * 
     */
    public TrafficTransitionDiagramData createTrafficTransitionDiagramData() {
        return new TrafficTransitionDiagramData();
    }

    /**
     * Create an instance of {@link AllGraphs }
     * 
     */
    public AllGraphs createAllGraphs() {
        return new AllGraphs();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link FlowData }
     * 
     */
    public FlowData createFlowData() {
        return new FlowData();
    }

    /**
     * Create an instance of {@link HistogramData }
     * 
     */
    public HistogramData createHistogramData() {
        return new HistogramData();
    }

    /**
     * Create an instance of {@link SpeedData }
     * 
     */
    public SpeedData createSpeedData() {
        return new SpeedData();
    }

    /**
     * Create an instance of {@link TravelTimeData }
     * 
     */
    public TravelTimeData createTravelTimeData() {
        return new TravelTimeData();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link CumulateVolumeLightedData }
     * 
     */
    public CumulateVolumeLightedData createCumulateVolumeLightedData() {
        return new CumulateVolumeLightedData();
    }

}
