package ru.cos.sim.visualizer.traffic.gui;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import javax.swing.JOptionPane;

/**
 *
 * @author ivan
 */
public class AskDialog extends javax.swing.JDialog {

	private static Object[] options = { "View report", "Cancel" };
	private java.awt.Frame parent;
	private JOptionPane optionPane;
	private String message = "Would you like to save the report?";
	private static int width = 294;
	private static int height = 131;
    /** Creates new form AskDialog */
    public AskDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
    }
    
    public AskDialog(java.awt.Frame parent, String message, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        this.message = message;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        jOptionPane1 = new javax.swing.JOptionPane();
        this.optionPane = jOptionPane1;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        //if (component != null) setLocationRelativeTo(component); else
        	//setLocationRelativeTo(parent);
        if (this.parent != null){
        	int x = this.parent.getX() + (this.parent.getWidth() - width)/2; 
            int y = this.parent.getY() + (this.parent.getHeight() - height)/2;
            setBounds(x, y, 350, 131);
            
        }
        setResizable(false);

        jOptionPane1.setMessage(message);
        jOptionPane1.setMessageType(javax.swing.JOptionPane.QUESTION_MESSAGE);
        jOptionPane1.setOptionType(javax.swing.JOptionPane.YES_NO_OPTION);
        
        jOptionPane1.setOptions(options);

        jOptionPane1.addPropertyChangeListener(
                new PropertyChangeListener() {
                    public void propertyChange(PropertyChangeEvent e) {
                        String prop = e.getPropertyName();
                        if (JOptionPane.VALUE_PROPERTY.equals(prop)){
                        	handleButtons();
                        }
                    }
                });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jOptionPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jOptionPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AskDialog dialog = new AskDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void handleButtons()
    {
    	if (this.isVisible()) this.setVisible(false);
    }
    
    public boolean getValue()
    {
    	try {
        	Object value = jOptionPane1.getValue();
        	if (value.equals(options[0])) return true; else return false;
    	} catch (Exception e)
    	{
    		return false;
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables

}
